### ISSUE TITLE
[ORGA] Helles Logo für BA

### ISSUE THREAD

**Issue by cagix** [Compiler-CampusMinden/CB-Vorlesung#60]
Helles Logo analog zum aktuellen Logo für den Bachelor-Kurs benötigt

**Comment by cagix** [comment]
@AMatutat Hast Du schon was?

**Comment by AMatutat** [comment]
Noch nicht, mach ich diese Woche fertig.

**Comment by AMatutat** [comment]
@cagix hast du irgendwo noch das das original File? Ich fürchte ich muss das ganze Nachzeichnen und hab leider keine Ahnung welche Auflösung ich verwendet habe. GitHub Skaliert das im Icon automatisch hoch

**Comment by cagix** [comment]
https://github.com/Compiler-CampusMinden/CB-Vorlesung/blob/master/static/images/logo.png ... wenn ich die git-historie verfolge, hast du das mal direkt ins git angeschleppt :)

**Comment by AMatutat** [comment]
@cagix @bcg7 Hab jetzt eine transparente Version. 
![lambda_transparent](https://user-images.githubusercontent.com/32962412/192256832-02eaa8cb-7652-4ac4-b4fe-188a3da88b84.png)

Könnt euch also eine Hintergrundfarbe wünschen. Hab mal das Internet gefragt welche Farben gut mit Orange gehen und ein paar Vorschläge gemacht: 


![green](https://user-images.githubusercontent.com/32962412/192256457-ebe2a85e-9e0b-49da-9931-55d9db0dabc2.png)
![blue](https://user-images.githubusercontent.com/32962412/192256718-e72cf652-4d6d-4026-a4a4-b9182ff5fe7a.png)
![pink](https://user-images.githubusercontent.com/32962412/192256721-b1305024-d060-41ab-b76d-18d4e57282b6.png)

**Comment by cagix** [comment]
@AMatutat Du bist unser Held :)

Für den Bachelor finde ich den grünen oder blauen Hintergrund ganz nett. Dabei gefällt mir das blaue sogar ein wenig mehr als das grüne. 

Allerdings wäre bei der grünen Variante der farbliche Unterschied zum Master mit dem schwarzen Hintergrund höher. 

Andererseits steckt das Logo auf der Webseite/Skript links oben in der Box - und die ist bereits grün. Damit ist die grüne Variante vielleicht nicht so gut. 

@AMatutat Noch eine Idee: Das Logo mit dem blauen Hintergrund, aber das Lambda in einer anderen Farbe? Eher ins gelbliche? 

<img width="500" alt="Screenshot 2022-09-26 at 12 47 57" src="https://user-images.githubusercontent.com/20356276/192258219-ed393121-af3d-4f96-9e25-7831d4dce066.png">

@bcg7 Was denkst Du?


@AMatutat Da Du nun nochmal neu gemalt hast: Könntest Du bitte noch eine Variante mit dem alten (schwarzen) Hintergrund machen? Dann sind sie symmetrisch :)

**Comment by AMatutat** [comment]
![blue_yellow](https://user-images.githubusercontent.com/32962412/192266618-d9f3acb5-ecc7-4756-a72e-36b2f52e57a0.png)


> @AMatutat Da Du nun nochmal neu gemalt hast: Könntest Du bitte noch eine Variante mit dem alten (schwarzen) Hintergrund machen? Dann sind sie symmetrisch :)

Ist nicht neu gemalt. Hab die Idee aufgegriffen das logo auszuschneiden. Ist also symmetrisch.

**Comment by cagix** [comment]
ah ok.

@bcg7 ich finde die blau-gelbe variante optisch sehr schön, das könnte auch gut zum grünen hintergrund im skript passen. was denkst du? oder sind wir da farblich zu nah an real existierenden firmen bzw. staaten?

**Comment by cagix** [comment]
@AMatutat Die blau-gelbe Variante ist der "Gewinner". Kannst Du bitte einen PR aufmachen und die Datei gegen [`static/images/logo.ba.png`](https://github.com/Compiler-CampusMinden/CB-Vorlesung/blob/master/static/images/logo.ba.png) austauschen?
