### ISSUE TITLE
[VL-BA] frontend/semantics/attribgrammars: ohne Bison/Flex

### ISSUE THREAD

**Issue by cagix** [Compiler-CampusMinden/CB-Vorlesung#67]

**Comment by cagix** [comment]
@bcg7 Die annotated slides habe ich aktualisiert. Aber die überarbeiteten Folien (die Quellen) hast Du hier noch nicht gepusht, oder?

**Comment by bcg7** [comment]
@cagix Die kommen noch.

**Comment by cagix** [comment]
> @cagix Die kommen noch.

alles klar :)
