### ISSUE TITLE
[ORGA] Builder in neues Repo auslagern

### ISSUE THREAD

**Issue by cagix** [Compiler-CampusMinden/CB-Vorlesung#80]
- [x] Neues public Repo für die Studis anlegen
- [x] Builder-Unterordner per `git subtree --push` in das neue Repo pushen
- [x] Wiki im neuen Repo ergänzen mit aktualisierter und gekürzter Doku
- [x] Links (Repo, Wiki) in Aufgabenblatt 01 und Orga/FAQ unterbringen (siehe auch #62)

siehe https://github.com/Compiler-CampusMinden/Mini-Python/milestone/1

---

@CrappyAlgorithm Wie weit ist das Mini-Python-Repo? Kann der Ordner gesplittet werden oder wird es da in den nächsten Tagen noch Änderungen geben?

@CrappyAlgorithm Wie weit ist die Doku, die den Sprachumfang von Mini-Python beschreibt? Kann die schon ins neue Wiki für die Studis?

@CrappyAlgorithm @mpeters4 Wenn ich den `git subtree --push` mache, dann landet der Inhalt des Builder-Ordners toplevel im neuen Repo. D.h. im Prinzip müsste ich in den Builder-Ordner noch den ganzen Readme/Contrib/License-Kram reintun, damit das "drüben" dann auch sichtbar wird. Andererseits ist das im Mini-Python-Repo dann dupliziert - hier liegt das ja eine Ebene höher nochmal alles rum (und zudem müssten die Links in den Sachen im Builder-Ordner alle auf das Studi-Repo zeigen). Seht ihr hier eine vernünftige Lösung? Wäre das eventuell der Punkt, den Ordner richtig aus dem Mini-Python-Repo zu lösen und nochmal neu als Git-Submodule einzubinden?

**Comment by CrappyAlgorithm** [comment]
> @CrappyAlgorithm Wie weit ist das Mini-Python-Repo? Kann der Ordner gesplittet werden oder wird es da in den nächsten Tagen noch Änderungen geben?

Im Builder kommen noch ein paar Änderungen, zb. die arithmetischen Operatoren müssen noch implementiert werden.
> 
> @CrappyAlgorithm Wie weit ist die Doku, die den Sprachumfang von Mini-Python beschreibt? Kann die schon ins neue Wiki für die Studis?

Die Doku für den Sprachumfang sollte soweit fertig sein. Es gibt ja noch die Besonderheiten, dass z.B. `a == b` als Methothenaufruf `a.__eq__(b)` an den Builder übergeben werden muss, aber das würde ich dann eher in einer einzelnen Doku zur Verwendung des Builders sehen.
> 
> @CrappyAlgorithm @mpeters4 Wenn ich den `git subtree --push` mache, dann landet der Inhalt des Builder-Ordners toplevel im neuen Repo. D.h. im Prinzip müsste ich in den Builder-Ordner noch den ganzen Readme/Contrib/License-Kram reintun, damit das "drüben" dann auch sichtbar wird. Andererseits ist das im Mini-Python-Repo dann dupliziert - hier liegt das ja eine Ebene höher nochmal alles rum (und zudem müssten die Links in den Sachen im Builder-Ordner alle auf das Studi-Repo zeigen). Seht ihr hier eine vernünftige Lösung? Wäre das eventuell der Punkt, den Ordner richtig aus dem Mini-Python-Repo zu lösen und nochmal neu als Git-Submodule einzubinden?

Das ist eine gute Frage, aber das weiß ich nun auch nicht. Ich habe mich aber generell auch noch nie mit den Git-Submodulen beschäftigt.

**Comment by CrappyAlgorithm** [comment]
Also mit dem Splitt würde ich noch 1-2 Wochen warten bis der Builder komplett fertig ist. Aber ich denke man könnte ja das Repo schon soweit erzeugen, damit man den Sprachumfang schonmal in den Wiki schieben kann. Alternativ müsste man den Sprachumfang für das erste Blatt anders zugänglich machen.

**Comment by cagix** [comment]
> Also mit dem Splitt würde ich noch 1-2 Wochen warten bis der Builder komplett fertig ist. Aber ich denke man könnte ja das Repo schon soweit erzeugen, damit man den Sprachumfang schonmal in den Wiki schieben kann. Alternativ müsste man den Sprachumfang für das erste Blatt anders zugänglich machen.

Hmmm, das erste Blatt muss früher raus. Nicht unbedingt diese Woche, aber nächste. 

Ich könnte ja das Studi-Repo "leer" anlegen und das Wiki freischalten und dort dann das von @CrappyAlgorithm bereinigte/aktualisierte http://github.com/Compiler-CampusMinden/Mini-Python/blob/main/doc/supported_features.md reinkopieren. Den Push mit den Daten kann man dann auch noch später machen. Das könnte so gehen, oder?

Habt ihr ne Idee, wie wir das mit den Lizenzen etc. machen? Das alles in den Builder-Ordner zu kopieren klingt irgendwie falsch. Alternativ könnte ich das im neuen Repo im Master anlegen, dann müsste man den Builder in einen Hilfsbranch pushen und anschließend mergen. Hmmm.

**Comment by CrappyAlgorithm** [comment]
> > Also mit dem Splitt würde ich noch 1-2 Wochen warten bis der Builder komplett fertig ist. Aber ich denke man könnte ja das Repo schon soweit erzeugen, damit man den Sprachumfang schonmal in den Wiki schieben kann. Alternativ müsste man den Sprachumfang für das erste Blatt anders zugänglich machen.
> 
> Hmmm, das erste Blatt muss früher raus. Nicht unbedingt diese Woche, aber nächste.
> 
> Ich könnte ja das Studi-Repo "leer" anlegen und das Wiki freischalten und dort dann das von @CrappyAlgorithm bereinigte/aktualisierte [http://github.com/Compiler-CampusMinden/Mini-Python/blob/main/doc/supported_features.md](https://github.com/Compiler-CampusMinden/Mini-Python/blob/main/doc/supported_features.md) reinkopieren. Den Push mit den Daten kann man dann auch noch später machen. Das könnte so gehen, oder?
> 
Genau das war auch mein Gedanke.

> Habt ihr ne Idee, wie wir das mit den Lizenzen etc. machen? Das alles in den Builder-Ordner zu kopieren klingt irgendwie falsch. Alternativ könnte ich das im neuen Repo im Master anlegen, dann müsste man den Builder in einen Hilfsbranch pushen und anschließend mergen. Hmmm.

Das mit dem Hilfsbranch klingt gut.

**Comment by cagix** [comment]
@CrappyAlgorithm dann sag bescheid, wenn du mit https://github.com/Compiler-CampusMinden/Mini-Python/blob/main/doc/supported_features.md soweit durch bist :)

**Comment by cagix** [comment]
@CrappyAlgorithm Ich habe das neue Repo für die Studis aufgemacht, dort solltest Du eine Wiki-Seite anlegen können. Wie besprochen - der aktualisierte Inhalt von http://github.com/Compiler-CampusMinden/Mini-Python/blob/main/doc/supported_features.md, nur ohne die letzten beiden Spalten.

**Comment by cagix** [comment]
all done in https://github.com/Compiler-CampusMinden/Mini-Python/milestone/1 ... closing.
